export const motherProjects = [
  {
    id: 1,
    number: "01",
    name: "Oxford Progressive Schools Regd.",
    shortName: "Oxford Progressive Schools",
    monogram: "/monograms/oxford.jpg",
    tagline: "Let's Restore The Planet — Concept-Based Modern Schooling",
    description:
      "Delivering international academic standards, conceptual STEM curriculum, and disciplined student development across campuses.",
    tag: "Mother Project 01",
    badgeColor: "bg-amber-500/10 text-amber-600 border-amber-300",
    gradient: "from-blue-900/10 via-amber-500/5 to-transparent",
    border: "border-amber-400/30 hover:border-amber-500",
    slug: "/SocietyAndClubs",
    image: "/tea_project_oxford.jpg",
  },
  {
    id: 2,
    number: "02",
    name: "Tabassum I.T & Skills Center",
    shortName: "Tabassum I.T & Skills Center",
    monogram: "/monograms/tabassum_it.jpg",
    tagline: "Computer & Soft IT Skills | Artificial Intelligence",
    description:
      "Empowering youth and educators with cutting-edge IT certifications, artificial intelligence, programming, and digital skills.",
    tag: "Mother Project 02",
    badgeColor: "bg-sky-500/10 text-sky-600 border-sky-300",
    gradient: "from-sky-900/10 via-cyan-500/5 to-transparent",
    border: "border-sky-400/30 hover:border-sky-500",
    slug: "/SocietyAndClubs",
    image: "/tea_project_it.jpg",
  },
  {
    id: 3,
    number: "03",
    name: "The Nest (School for Triumph)",
    shortName: "The Nest (NEST)",
    monogram: "/monograms/nest.jpg",
    tagline: "Knowledge, Wisdom, Purity — Experiential Education & Triumph",
    description:
      "Fostering creative problem-solving, extracurricular excellence, and progressive academic mentorship for young achievers.",
    tag: "Mother Project 03",
    badgeColor: "bg-teal-500/10 text-teal-600 border-teal-300",
    gradient: "from-teal-900/10 via-teal-500/5 to-transparent",
    border: "border-teal-400/30 hover:border-teal-500",
    slug: "/SocietyAndClubs",
    image: "/tea_project_nest.jpg",
  },
  {
    id: 4,
    number: "04",
    name: "Idara Taleemat-e-Nabawia Lahore",
    shortName: "Idara Taleemat-e-Nabawia",
    monogram: "/monograms/idara.jpg",
    tagline: "Value-Based Education, Spiritual Heritage & Moral Grooming",
    description:
      "Providing deep cultural roots, ethical foundations, and community enlightenment rooted in exemplary moral principles.",
    tag: "Mother Project 04",
    badgeColor: "bg-rose-500/10 text-rose-600 border-rose-300",
    gradient: "from-rose-900/10 via-rose-500/5 to-transparent",
    border: "border-rose-400/30 hover:border-rose-500",
    slug: "/SocietyAndClubs",
    image: "/tea_project_idara.jpg",
  },
  {
    id: 5,
    number: "05",
    name: "Al Qalam School (القلم اسکول)",
    shortName: "Al Qalam School",
    monogram: "/monograms/alqalam.jpg",
    tagline: "Success is our aim — Pen of Knowledge & Academic Excellence",
    description:
      "Dedicated to academic excellence, foundational learning, and student success with high educational standards.",
    tag: "Mother Project 05",
    badgeColor: "bg-blue-500/10 text-blue-600 border-blue-300",
    gradient: "from-blue-900/10 via-blue-500/5 to-transparent",
    border: "border-blue-400/30 hover:border-blue-500",
    slug: "/SocietyAndClubs",
    image: "/tea_student1.jpg",
  },
  {
    id: 6,
    number: "06",
    name: "National Ulama Council Pakistan",
    shortName: "National Ulama Council",
    monogram: "/monograms/ulama_council.jpg",
    tagline: "Moral Leadership, Educational Harmony & National Values",
    description:
      "Guiding youth and communities with ethical values, moral leadership, and comprehensive educational advocacy across Pakistan.",
    tag: "Mother Project 06",
    badgeColor: "bg-emerald-500/10 text-emerald-600 border-emerald-300",
    gradient: "from-emerald-900/10 via-emerald-500/5 to-transparent",
    border: "border-emerald-400/30 hover:border-emerald-500",
    slug: "/SocietyAndClubs",
    image: "/tea_student2.jpg",
  },
];

export const alliesProjects = [
  {
    id: 1,
    name: "IQRA Madinat-Ul-Atfal Group of Schools",
    monogram: "/monograms/iqra.svg",
    tagline: "Character Building & Moral Grooming",
  },
  {
    id: 2,
    name: "Kids Education School System",
    monogram: "/monograms/kids_education.svg",
    tagline: "Foundational Learning & Child Mentorship",
  },
  {
    id: 3,
    name: "Fikr e Raat",
    monogram: "/monograms/fikr_e_raat.svg",
    tagline: "Educational Enlightenment & Intellectual Growth",
  },
];
