export const motherProjects = [
  {
    id: 1,
    number: "01",
    name: "Oxford Progressive Schools Regd.",
    shortName: "Oxford Progressive Schools",
    monogram: "/monograms/oxford.svg",
    tagline: "Concept-based modern schooling & strong academic foundations.",
    description:
      "Delivering international academic standards, conceptual STEM curriculum, and disciplined student development across campuses.",
    tag: "Mother Project 01",
    badgeColor: "bg-amber-500/10 text-amber-600 border-amber-300",
    gradient: "from-blue-900/10 via-amber-500/5 to-transparent",
    border: "border-amber-400/40 hover:border-amber-500",
    slug: "/SocietyAndClubs",
    image: "/tea_project_oxford.jpg",
  },
  {
    id: 2,
    number: "02",
    name: "IQRA Madinat-Ul-Atfal Group of Schools Regd.",
    shortName: "IQRA Madinat-Ul-Atfal",
    monogram: "/monograms/iqra.svg",
    tagline: "Character building, moral grooming & core ethical values.",
    description:
      "Integrating holistic character education with contemporary syllabus to nurture enlightened, responsible young learners.",
    tag: "Mother Project 02",
    badgeColor: "bg-emerald-500/10 text-emerald-600 border-emerald-300",
    gradient: "from-emerald-900/10 via-emerald-500/5 to-transparent",
    border: "border-emerald-400/40 hover:border-emerald-500",
    slug: "/SocietyAndClubs",
    image: "/tea_project_iqra.jpg",
  },
  {
    id: 3,
    number: "03",
    name: "Tabassum I.T & Skills Center",
    shortName: "Tabassum I.T & Skills Center",
    monogram: "/monograms/it_skills.svg",
    tagline: "Future-ready technology, digital education & practical computing.",
    description:
      "Empowering students and educators with cutting-edge IT certifications, coding fundamentals, and digital literacy for modern careers.",
    tag: "Mother Project 03",
    badgeColor: "bg-sky-500/10 text-sky-600 border-sky-300",
    gradient: "from-sky-900/10 via-cyan-500/5 to-transparent",
    border: "border-sky-400/40 hover:border-sky-500",
    slug: "/SocietyAndClubs",
    image: "/tea_project_it.jpg",
  },
  {
    id: 4,
    number: "04",
    name: "Idara Taleemat-e-Nabawia Lahore",
    shortName: "Idara Taleemat-e-Nabawia",
    monogram: "/monograms/idara.svg",
    tagline: "Value-based education, spiritual heritage & holistic growth.",
    description:
      "Providing deep cultural roots, ethical foundations, and community enlightenment rooted in exemplary moral principles.",
    tag: "Mother Project 04",
    badgeColor: "bg-rose-500/10 text-rose-600 border-rose-300",
    gradient: "from-rose-900/10 via-rose-500/5 to-transparent",
    border: "border-rose-400/40 hover:border-rose-500",
    slug: "/SocietyAndClubs",
    image: "/tea_project_idara.jpg",
  },
  {
    id: 5,
    number: "05",
    name: "The Nest (National Educational School for Triumph)",
    shortName: "The Nest (School for Triumph)",
    monogram: "/monograms/nest.svg",
    tagline: "Experiential education, innovation & triumphant student leadership.",
    description:
      "Fostering creative problem-solving, extracurricular excellence, and progressive academic mentorship for young achievers.",
    tag: "Mother Project 05",
    badgeColor: "bg-teal-500/10 text-teal-600 border-teal-300",
    gradient: "from-teal-900/10 via-teal-500/5 to-transparent",
    border: "border-teal-400/40 hover:border-teal-500",
    slug: "/SocietyAndClubs",
    image: "/tea_project_nest.jpg",
  },
];

export const alliesProjects = [
  {
    id: 1,
    name: "Al Qalam School",
    monogram: "/monograms/alqalam.svg",
    tagline: "Pen of Knowledge & Academic Excellence",
  },
  {
    id: 2,
    name: "Kids Education School System",
    monogram: "/monograms/kids_education.svg",
    tagline: "Foundational Learning & Child Mentorship",
  },
  {
    id: 3,
    name: "Fikr e Raat",
    monogram: "/monograms/fikr_e_raat.svg",
    tagline: "Educational Enlightenment & Intellectual Growth",
  },
  {
    id: 4,
    name: "National Ulama Council Pakistan",
    monogram: "/monograms/ulama_council.svg",
    tagline: "Moral Leadership & National Values",
  },
];
