export const motherProjects = [
  {
    id: 1,
    number: "01",
    name: "Oxford Progressive Schools Regd.",
    shortName: "Oxford Progressive Schools",
    monogram: "/monograms/oxford.jpg",
    tagline: "Let's Restore The Planet — Concept-Based Modern Schooling",
    description:
      "Delivering international academic standards, conceptual STEM curriculum, and disciplined student development across campuses.",
    tag: "Mother Project 01",
    badgeColor: "bg-amber-500/10 text-amber-600 border-amber-300",
    gradient: "from-blue-900/10 via-amber-500/5 to-transparent",
    border: "border-amber-400/30 hover:border-amber-500",
    slug: "/SocietyAndClubs",
    image: "/tea_project_oxford.jpg",
  },
  {
    id: 2,
    number: "02",
    name: "Tabassum I.T & Skills Center",
    shortName: "Tabassum I.T & Skills Center",
    monogram: "/monograms/tabassum_it.jpg",
    tagline: "Computer & Soft IT Skills | Artificial Intelligence",
    description:
      "Empowering youth and educators with cutting-edge IT certifications, artificial intelligence, programming, and digital skills.",
    tag: "Mother Project 02",
    badgeColor: "bg-sky-500/10 text-sky-600 border-sky-300",
    gradient: "from-sky-900/10 via-cyan-500/5 to-transparent",
    border: "border-sky-400/30 hover:border-sky-500",
    slug: "/SocietyAndClubs",
    image: "/tea_project_it.jpg",
  },
  {
    id: 3,
    number: "03",
    name: "IQRA Madinat-Ul-Atfal Group of Schools",
    shortName: "IQRA Madinat-Ul-Atfal",
    monogram: "/monograms/iqra.jpg",
    tagline: "اقراء مدینۃ الاطفال — Character Building & Moral Grooming",
    description:
      "Integrating holistic character education with contemporary syllabus to nurture enlightened, responsible young learners.",
    tag: "Mother Project 03",
    badgeColor: "bg-emerald-500/10 text-emerald-600 border-emerald-300",
    gradient: "from-emerald-900/10 via-emerald-500/5 to-transparent",
    border: "border-emerald-400/30 hover:border-emerald-500",
    slug: "/SocietyAndClubs",
    image: "/tea_project_iqra.jpg",
  },
  {
    id: 4,
    number: "04",
    name: "The Nest (School for Triumph)",
    shortName: "The Nest (NEST)",
    monogram: "/monograms/nest.jpg",
    tagline: "Knowledge, Wisdom, Purity — Experiential Education & Triumph",
    description:
      "Fostering creative problem-solving, extracurricular excellence, and progressive academic mentorship for young achievers.",
    tag: "Mother Project 04",
    badgeColor: "bg-teal-500/10 text-teal-600 border-teal-300",
    gradient: "from-teal-900/10 via-teal-500/5 to-transparent",
    border: "border-teal-400/30 hover:border-teal-500",
    slug: "/SocietyAndClubs",
    image: "/tea_project_nest.jpg",
  },
  {
    id: 5,
    number: "05",
    name: "Idara Taleemat-e-Nabawia Lahore",
    shortName: "Idara Taleemat-e-Nabawia",
    monogram: "/monograms/idara.jpg",
    tagline: "ادارہ تعلیماتِ نبویہ — Value-Based Education & Spiritual Heritage",
    description:
      "Providing deep cultural roots, ethical foundations, and community enlightenment rooted in exemplary moral principles.",
    tag: "Mother Project 05",
    badgeColor: "bg-rose-500/10 text-rose-600 border-rose-300",
    gradient: "from-rose-900/10 via-rose-500/5 to-transparent",
    border: "border-rose-400/30 hover:border-rose-500",
    slug: "/SocietyAndClubs",
    image: "/tea_project_idara.jpg",
  },
  {
    id: 6,
    number: "06",
    name: "Kids Education School System®",
    shortName: "Kids Education School System",
    monogram: "/monograms/kids_education.jpg",
    tagline: "Inspire • Learn • Lead — Empowering Future Leaders (Since 2018)",
    description:
      "Comprehensive early-years and primary education fostering curiosity, confidence, and leadership in young minds.",
    tag: "Mother Project 06",
    badgeColor: "bg-green-500/10 text-green-600 border-green-300",
    gradient: "from-green-900/10 via-green-500/5 to-transparent",
    border: "border-green-400/30 hover:border-green-500",
    slug: "/SocietyAndClubs",
    image: "/tea_student1.jpg",
  },
  {
    id: 7,
    number: "07",
    name: "Al Qalam School (القلم اسکول)",
    shortName: "Al Qalam School",
    monogram: "/monograms/alqalam.jpg",
    tagline: "Success is our aim — Pen of Knowledge & Academic Excellence",
    description:
      "Dedicated to academic excellence, foundational learning, and student success with high educational standards.",
    tag: "Mother Project 07",
    badgeColor: "bg-blue-500/10 text-blue-600 border-blue-300",
    gradient: "from-blue-900/10 via-blue-500/5 to-transparent",
    border: "border-blue-400/30 hover:border-blue-500",
    slug: "/SocietyAndClubs",
    image: "/tea_student2.jpg",
  },
  {
    id: 8,
    number: "08",
    name: "National Ulama Council Pakistan",
    shortName: "National Ulama Council",
    monogram: "/monograms/ulama_council.jpg",
    tagline: "نیشنل علماء کونسل پاکستان — Moral Leadership & National Values",
    description:
      "Guiding youth and communities with ethical values, moral leadership, and comprehensive educational advocacy across Pakistan.",
    tag: "Mother Project 08",
    badgeColor: "bg-emerald-500/10 text-emerald-600 border-emerald-300",
    gradient: "from-emerald-900/10 via-emerald-500/5 to-transparent",
    border: "border-emerald-400/30 hover:border-emerald-500",
    slug: "/SocietyAndClubs",
    image: "/tea_project_iqra.jpg",
  },
  {
    id: 9,
    number: "09",
    name: "Fikr-e-Rast (فکرِ راست)",
    shortName: "Fikr-e-Rast",
    monogram: "/monograms/fikr_e_rast.jpg",
    tagline: "فکرِ راست — Educational Enlightenment & Intellectual Guidance",
    description:
      "Promoting intellectual growth, thoughtful dialogue, ethical consciousness, and positive national impact.",
    tag: "Mother Project 09",
    badgeColor: "bg-amber-500/10 text-amber-600 border-amber-300",
    gradient: "from-amber-900/10 via-amber-500/5 to-transparent",
    border: "border-amber-400/30 hover:border-amber-500",
    slug: "/SocietyAndClubs",
    image: "/tea_student1.jpg",
  },
  {
    id: 10,
    number: "10",
    name: "Tabassum Educational Alliance Regd.",
    shortName: "TEA Regd. Head Office",
    monogram: "/monograms/tea_main.jpg",
    tagline: "ہم سفر ہر قدم — The Fastest Growing Educational Network",
    description:
      "The apex governing body orchestrating academic quality, teacher training, curriculum standards, and network growth since 2008.",
    tag: "Apex Alliance 10",
    badgeColor: "bg-sky-500/10 text-sky-600 border-sky-300",
    gradient: "from-sky-900/10 via-cyan-500/5 to-transparent",
    border: "border-sky-400/30 hover:border-sky-500",
    slug: "/AboutUs",
    image: "/tea_student2.jpg",
  },
];

export const alliesProjects = [
  {
    id: 1,
    name: "Kids Education School System®",
    monogram: "/monograms/kids_education.jpg",
    tagline: "Inspire • Learn • Lead",
  },
  {
    id: 2,
    name: "Al Qalam School (القلم اسکول)",
    monogram: "/monograms/alqalam.jpg",
    tagline: "Pen of Knowledge & Academic Excellence",
  },
  {
    id: 3,
    name: "National Ulama Council Pakistan",
    monogram: "/monograms/ulama_council.jpg",
    tagline: "Moral Leadership & National Values",
  },
  {
    id: 4,
    name: "Fikr-e-Rast (فکرِ راست)",
    monogram: "/monograms/fikr_e_rast.jpg",
    tagline: "Educational Enlightenment & Guidance",
  },
];
